// This file overrides the built-in Apache httpd (PHP, HTML) runner
// For more information see http://docs.c9.io:8080/#!/api/run-method-run
{
  "cmd": [
    "bash",
    "--login",
    "-c",
    "cp /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load",
    "source /etc/apache2/envvars && apache2 -X"
  ],
  "selector": "^.*\\.(php|phtml|html|shtml)$",
  "info": "Started Apache httpd, serving \\033[01;34m$hostname_path\\033[00m."
}